export const SET_START_SWIPER_INDEX = 'SET_START_SWIPER_INDEX'
export const SET_END_SWIPER_INDEX = 'SET_END_SWIPER_INDEX'
export const SET_COMMUNITY_OVERLAY = 'SET_COMMUNITY_OVERLAY'
export const SET_OPTIMAL_OVERLAY = 'SET_OPTIMAL_OVERLAY'
